/**
 * The route list the build prerenders, plus the Chromium lookup that powers it.
 *
 * WHY THIS EXISTS
 * ---------------
 * The site is a client-rendered SPA, so every URL used to serve the same `index.html`. A
 * crawler that does not execute JavaScript — which is every social scraper: Facebook,
 * LinkedIn, WhatsApp, Slack, X — therefore saw the HOMEPAGE title and description on every
 * shared link. Prerendering writes a real `dist/<route>/index.html` per route with that
 * route's own <title>, description, canonical, Open Graph tags and JSON-LD.
 *
 * WHAT IS PRERENDERED, AND WHY NOT EVERYTHING
 * -------------------------------------------
 * By default: the marketing routes plus every category and subcategory (~40 pages, a few
 * seconds). The 355 product pages are opt-in behind `PRERENDER_PRODUCTS=1`, because each
 * one costs a real browser navigation and turns a 3-second build into a multi-minute one.
 * Google renders JavaScript, so product pages are still indexed without this; turn it on
 * when the long-tail product listings matter more than build time.
 */
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'src', 'data');

/** Mirrors the public routes in src/App.jsx. Admin routes are deliberately excluded. */
const STATIC_ROUTES = [
  '/',
  '/about',
  '/products',
  '/contact',
  '/manufacturing',
  '/projects-gallery',
  '/rfq',
  '/certifications',
  '/faq',
  '/downloads',
  '/careers',
  '/privacy-policy',
  '/terms',
  // Prerendered so the search index carries it: it is a real page a visitor may look for.
  '/cookie-policy',
];

export function getPrerenderRoutes({ includeProducts = false } = {}) {
  const routes = [...STATIC_ROUTES];

  // categories.json is generated by gen-categories.mjs, which `prebuild` runs first. If it
  // is missing (someone ran `vite build` directly) fall back to the static routes rather
  // than crashing the build.
  const categoriesPath = join(DATA, 'categories.json');
  if (existsSync(categoriesPath)) {
    const categories = JSON.parse(readFileSync(categoriesPath, 'utf8'));
    for (const c of categories) {
      routes.push(`/products/${c.slug}`);
      for (const s of c.subcategories) routes.push(`/products/${c.slug}/${s.slug}`);
    }
  }

  if (includeProducts) {
    const productsPath = join(DATA, 'products.json');
    if (existsSync(productsPath)) {
      const products = JSON.parse(readFileSync(productsPath, 'utf8'));
      for (const p of products) {
        if (p.id === undefined || p.id === null) continue;
        routes.push(`/product/${p.id}`);
      }
    }
  }

  return [...new Set(routes)];
}

/**
 * Puppeteer's own Chromium download is ~150 MB and is commonly blocked by install-script
 * policies (it was here). Every Windows machine already ships Edge, and most dev machines
 * have Chrome, so reuse one of those instead. `PRERENDER_BROWSER` overrides the search,
 * which is how a Linux CI box points at its own chromium.
 *
 * Returns null when nothing is found — the caller then SKIPS prerendering with a warning
 * rather than failing the build, so a deploy never breaks over a missing browser.
 */
export function findChromium() {
  if (process.env.PRERENDER_BROWSER) {
    return existsSync(process.env.PRERENDER_BROWSER) ? process.env.PRERENDER_BROWSER : null;
  }

  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ];

  return candidates.find((p) => existsSync(p)) || null;
}
