/**
 * The route list the build prerenders, plus the Chromium lookup that powers it.
 *
 * WHY THIS EXISTS
 * ---------------
 * The site is a client-rendered SPA, so every URL used to serve the same `index.html`. A
 * crawler that does not execute JavaScript — which is every social scraper: Facebook,
 * LinkedIn, WhatsApp, Slack, X — therefore saw the HOMEPAGE title and description on every
 * shared link. Prerendering writes a real `dist/<route>/index.html` per route with that
 * route's own <title>, description, canonical, Open Graph tags and JSON-LD.
 *
 * WHAT IS PRERENDERED
 * -------------------
 * Locally: the marketing routes plus every category and subcategory, in every live
 * language. About 530 pages, roughly 20 seconds on top of the JS build.
 *
 * On Vercel: that plus all 355 product pages, again in every language, because
 * vercel.json sets `PRERENDER_PRODUCTS=1`. About 4,800 pages and roughly 10 minutes.
 *
 * Products are worth those minutes. Without prerendering, a product URL serves the plain
 * SPA shell, whose canonical says "this page is the homepage" and whose title is the
 * homepage title. Google then treats all 355 product pages as duplicates of the homepage
 * and indexes none of them, which is the single largest SEO problem the site had. Google
 * executing JavaScript later does not undo a canonical it was handed in the HTML.
 *
 * Build time scales with pages times live languages, so adding a language adds about a
 * minute. If that ever becomes the binding constraint, drop `PRERENDER_PRODUCTS` for
 * preview deployments rather than for production.
 */
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';
import { liveLocales } from '../src/i18n/languages.js';
import { posts } from '../src/data/blog.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'src', 'data');

/** Mirrors the public routes in src/App.jsx. Admin routes are deliberately excluded. */
const STATIC_ROUTES = [
  '/',
  '/about',
  '/products',
  '/contact',
  '/manufacturing',
  '/projects-gallery',
  '/certifications',
  '/faq',
  '/downloads',
  '/export',
  '/blog',
  '/careers',
  '/privacy-policy',
  '/terms',
  // Prerendered so the search index carries it: it is a real page a visitor may look for.
  '/cookie-policy',
  /**
   * Not a page anyone navigates to: React Router's catch-all renders NotFound here, and
   * scripts/make-404.mjs copies the result to dist/404.html, which is the body Vercel serves
   * with a real 404 status. It carries noindex and is kept out of the sitemap.
   */
  '/404',
];

export function getPrerenderRoutes({ includeProducts = false } = {}) {
  const routes = [...STATIC_ROUTES];

  /**
   * Article pages, read from the same module the site renders, so publishing an article is
   * one edit rather than three. blog.js is plain data with no JSX, which is why this file
   * can import it even though vite.config loads it before any JSX pipeline exists.
   */
  for (const p of posts) routes.push(`/blog/${p.slug}`);

  // categories.json is generated by gen-categories.mjs, which `prebuild` runs first. If it
  // is missing (someone ran `vite build` directly) fall back to the static routes rather
  // than crashing the build.
  const categoriesPath = join(DATA, 'categories.json');
  if (existsSync(categoriesPath)) {
    const categories = JSON.parse(readFileSync(categoriesPath, 'utf8'));
    for (const c of categories) {
      routes.push(`/products/${c.slug}`);
      for (const s of c.subcategories) routes.push(`/products/${c.slug}/${s.slug}`);
    }
  }

  if (includeProducts) {
    const productsPath = join(DATA, 'products.json');
    if (existsSync(productsPath)) {
      const products = JSON.parse(readFileSync(productsPath, 'utf8'));
      for (const p of products) {
        if (p.id === undefined || p.id === null) continue;
        routes.push(`/product/${p.id}`);
      }
    }
  }

  /**
   * Every LIVE language re-renders the full route list under its own prefix — /de/about is
   * its own prerendered page with German copy and meta (the SPA reads the prefix and comes
   * up in that language; see App.jsx). While no locale is live this adds nothing and the
   * build is exactly the English build it always was. Expect build time to scale with the
   * number of live languages — that is the known, accepted cost of Option B.
   */
  const base = [...new Set(routes)];
  const localized = liveLocales().flatMap((code) => base.map((r) => (r === '/' ? `/${code}` : `/${code}${r}`)));

  return [...base, ...localized];
}

/**
 * Puppeteer downloads its own Chrome into a cache directory on install. Find it there,
 * synchronously, without importing puppeteer.
 *
 * Why not just call puppeteer.executablePath(): in Puppeteer 23 and later that returns a
 * Promise, and this whole lookup runs at the top of vite.config.js where a Promise cannot
 * be awaited. A directory scan is sync, has no import cost, and answers the only question
 * that matters: is there a browser on disk.
 *
 * Layout: <cache>/chrome/<platform>-<version>/chrome-<platform>/chrome[.exe]
 * The newest version directory wins, so an upgraded Puppeteer does not keep launching the
 * browser it shipped with two releases ago.
 */
function findPuppeteerChrome() {
  const cacheRoot = process.env.PUPPETEER_CACHE_DIR || join(homedir(), '.cache', 'puppeteer');
  const chromeRoot = join(cacheRoot, 'chrome');
  if (!existsSync(chromeRoot)) return null;

  let versions;
  try {
    versions = readdirSync(chromeRoot, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort()
      .reverse();
  } catch {
    return null;
  }

  for (const version of versions) {
    const dir = join(chromeRoot, version);
    let inner;
    try {
      inner = readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);
    } catch {
      continue;
    }
    for (const folder of inner) {
      for (const bin of ['chrome', 'chrome.exe', 'Google Chrome for Testing']) {
        const candidate = join(dir, folder, bin);
        if (existsSync(candidate)) return candidate;
      }
    }
  }
  return null;
}

/**
 * Where the build finds a browser to prerender with, in order of preference.
 *
 * PRERENDER_BROWSER wins, which is how a CI box points at its own binary. Then Puppeteer's
 * own download, which is what makes this work on Vercel: the build command installs it (see
 * vercel.json) and every deploy then ships real prerendered HTML. Then the browsers a
 * developer machine already has, so nobody needs a second 150 MB copy locally.
 *
 * Returns null when nothing is found. The caller then SKIPS prerendering with a warning
 * rather than failing the build, so a deploy never breaks over a missing browser. That
 * fallback is a safety net, NOT the normal path: a deploy that takes it serves the same
 * homepage title and canonical on every URL, which is what P1 and P2 of the SEO programme
 * were about. scripts/check-prerender.mjs fails the build instead of letting that ship.
 */
/**
 * Resolve a browser the build can actually PRERENDER with, and prove it before returning it.
 *
 * THE BUG THIS EXISTS TO PREVENT
 * ------------------------------
 * Finding a browser binary is not the same as being able to run one. Puppeteer's bundled
 * Chrome is an ordinary desktop build: it downloads onto any machine, but it needs a
 * desktop Linux's shared libraries (libnss3, libatk, libgbm and friends) to start. A minimal
 * cloud build container has none of them.
 *
 * Before this, the lookup only checked that a file existed. On Vercel that meant: browser
 * "found", handed to the prerender plugin, plugin launches it, launch fails, the exception
 * takes the whole build down. Four deploys failed that way. The previous behaviour was not
 * better, it just failed differently: no browser was found at all, prerendering was skipped,
 * and the build happily shipped one shell for all 4,800 URLs.
 *
 * So each candidate is LAUNCHED here, headless, and discarded. Whatever survives that can
 * render pages. If nothing survives, this returns null and the caller skips prerendering
 * with a loud warning, which keeps a browser problem from blocking every deploy.
 *
 * Order matters: on Linux the serverless Chromium goes first, because it is the one built
 * for this case and carries its own libraries.
 *
 * Returns { executablePath, args, source } or null.
 */
export async function resolveBrowser() {
  const candidates = [];

  if (process.env.PRERENDER_BROWSER) {
    candidates.push({ executablePath: process.env.PRERENDER_BROWSER, args: [], source: 'PRERENDER_BROWSER' });
  }

  // Linux only: this package ships a Linux binary, and on a developer's Windows or macOS
  // machine the ordinary lookups below already find a real browser.
  if (process.platform === 'linux') {
    try {
      const mod = await import('@sparticuz/chromium');
      const chromium = mod.default ?? mod;
      const executablePath = await chromium.executablePath();
      if (executablePath) {
        candidates.push({ executablePath, args: chromium.args ?? [], source: '@sparticuz/chromium' });
      }
    } catch {
      // Not installed, or failed to unpack. The other candidates still get their turn.
    }
  }

  const sync = findChromium();
  if (sync) candidates.push({ executablePath: sync, args: [], source: 'system or puppeteer cache' });

  for (const candidate of candidates) {
    if (!candidate.executablePath || !existsSync(candidate.executablePath)) continue;
    if (await canLaunch(candidate)) return candidate;
    console.warn(`[prerender] ${candidate.source} at ${candidate.executablePath} cannot launch here; trying the next option.`);
  }
  return null;
}

/** Start the browser and close it again. The only reliable test that it works. */
async function canLaunch({ executablePath, args }) {
  let browser;
  try {
    const { default: puppeteer } = await import('puppeteer');
    browser = await puppeteer.launch({
      executablePath,
      headless: true,
      args: [...new Set(['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', ...args])],
      timeout: 30000,
    });
    return true;
  } catch (err) {
    console.warn(`[prerender] launch test failed: ${String(err?.message || err).split('\n')[0]}`);
    return false;
  } finally {
    try { await browser?.close(); } catch { /* the process may already be gone */ }
  }
}

export function findChromium() {
  if (process.env.PRERENDER_BROWSER) {
    return existsSync(process.env.PRERENDER_BROWSER) ? process.env.PRERENDER_BROWSER : null;
  }

  const puppeteerChrome = findPuppeteerChrome();
  if (puppeteerChrome) return puppeteerChrome;

  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ];

  return candidates.find((p) => existsSync(p)) || null;
}
